from django.db import models

# Create your models here.
class resumeModel(models.Model):
    profileImage = models.ImageField(upload_to='media/resume')
    fullName = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    description = models.TextField()
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    phone = models.CharField(max_length=17)
    email = models.CharField(max_length=100)
    projects = models.IntegerField()
    followers = models.CharField(max_length=100)
    likes = models.CharField(max_length=100)
    about = models.TextField()
    facebook = models.CharField(max_length=100)
    github = models.CharField(max_length=100)
    linkedin = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    university = models.CharField(max_length=100)
    grad_year = models.CharField(max_length=100)
    institute = models.CharField(max_length=100)
    progress = models.CharField(max_length=100)
    html = models.IntegerField()
    css = models.IntegerField()
    react = models.IntegerField()
    vue = models.IntegerField()
    python = models.IntegerField()
    django = models.IntegerField()
    photoshop = models.IntegerField()
    sublime = models.IntegerField()
    git = models.IntegerField()
    npm = models.IntegerField()
