from django.db import models

# Create your models here.
class resumeModel(models.Model):
    profileImage = models.ImageField(upload_to='media/resume', null=True)
    fullName = models.CharField(max_length=100, null=True)
    profession = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    city = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=17, null=True)
    email = models.CharField(max_length=100, null=True)
    projects = models.IntegerField(null=True)
    followers = models.CharField(max_length=100, null=True)
    likes = models.CharField(max_length=100, null=True)
    about = models.TextField(null=True)
    facebook = models.CharField(max_length=100, null=True)
    github = models.CharField(max_length=100, null=True)
    linkedin = models.CharField(max_length=100, null=True)
    department = models.CharField(max_length=100, null=True)
    university = models.CharField(max_length=100, null=True)
    grad_year = models.CharField(max_length=100, null=True)
    institute = models.CharField(max_length=100, null=True)
    progress = models.CharField(max_length=100, null=True)
    html = models.IntegerField(null=True)
    css = models.IntegerField(null=True)
    react = models.IntegerField(null=True)
    vue = models.IntegerField(null=True)
    python = models.IntegerField(null=True)
    django = models.IntegerField(null=True)
    photoshop = models.IntegerField(null=True)
    sublime = models.IntegerField(null=True)
    git = models.IntegerField(null=True)
    npm = models.IntegerField(null=True)
