# Generated by Django 5.2.3 on 2025-06-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(upload_to='media/resume')),
                ('fullName', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.CharField(max_length=100)),
                ('projects', models.IntegerField()),
                ('followers', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('grad_year', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('html', models.IntegerField()),
                ('css', models.IntegerField()),
                ('react', models.IntegerField()),
                ('vue', models.IntegerField()),
                ('python', models.IntegerField()),
                ('django', models.IntegerField()),
                ('photoshop', models.IntegerField()),
                ('sublime', models.IntegerField()),
                ('git', models.IntegerField()),
                ('npm', models.IntegerField()),
            ],
        ),
    ]
