# Generated by Django 5.2.3 on 2025-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='css',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='django',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='followers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='git',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='grad_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='html',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='likes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='npm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='phone',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='photoshop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='media/resume'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='progress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='python',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='react',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='sublime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='vue',
            field=models.IntegerField(null=True),
        ),
    ]
